### ISSUE TITLE
Multiple marks at the same node not working

### ISSUE THREAD

**Issue by muhammedmagdi** [palessit/slate-html-mui#18]
Based on the codesandbox: https://codesandbox.io/s/wonderful-ramanujan-jtq41
When I try to add bold, italic and underline at the same element and then save to local storage and console.log(str);
it includes only the first mark I have selected and the other marks aren't saved.

**Comment by alexichepura** [comment]
@muhammedmagdi ,
Thanks you for the reporting!

**Comment by alexichepura** [comment]
fixed and released in 0.9.1
